# +++++ Configuration ++++++

# --- FeatureUnitConfiguration---
# TODO:
## classification
#startPos=0
#queryLimit=500
#fetchSize=500

# in subfolder resources/classification/trainingSets
#trainingDataFile=trainingdata_anonymized.tsv

input_path: '..\..\quenfo_data\sqlite\orm\text_kernel_orm_2018_03.db'

fus_config:
  normalize: true
  stem: true
  filterSW: true
  nGrams: {3,4}
  continousNGrams: true



resources:
  stopwords_path: '..\..\quenfo_data\resources\classification\stopwords.txt'
