# +++++ Configuration ++++++

# --- FeatureUnitConfiguration---
# TODO:
## classification
#startPos=0
#queryLimit=500
#fetchSize=500

# in subfolder resources/classification/trainingSets
#trainingDataFile=trainingdata_anonymized.tsv

fus_config:
  normalize: true
  stem: true
  filterSW: true
  # Generates sets of 3-Grams and 4-Grams joined in one list --> other valid options: {3} or {2,3,6} ...
  nGrams: {3,4}
  continuousNGrams: false



query_limit: 50

mode : overwrite
#mode : append

resources:
  input_path: '..\..\quenfo_data\sqlite\orm\text_kernel_orm_2018_03.db'
  traindata_path: '..\..\traindata_sql.db'
  stopwords_path: '..\..\quenfo_data\resources\classification\stopwords.txt'
