# +++++ Configuration ++++++

# --- FeatureUnitConfiguration---
# Define processing steps for featureunits.
fus_config:
  normalize: true
  stem: true
  filterSW: true
  # Generates sets of 3-Grams and 4-Grams joined in one list --> other valid options: {3} or {2,3,6} ...
  nGrams: {3,4}
  continuousNGrams: false

# --- General Parameters ---
# Number of JobAds to query
query_limit: 500
# Check if JobAds are already in Output-Database and decide to append or overwrite new data
mode : overwrite
# or mode : append

# --- Paths ---
resources:
  # Path for Input data to be classified
  input_path: '..\..\quenfo_data\sqlite\orm\text_kernel_orm_2018_03.db'
  # Path for Train data to be used for training process
  traindata_path: '..\..\traindata_sql.db'
  # Path for file with stopwords
  stopwords_path: '..\..\quenfo_data\resources\classification\stopwords.txt'
  # Path for regex file
  regex_path: '..\..\quenfo_data\resources\classification\regex.txt'

  # Paths for information extraction
  competences_path: '..\..\quenfo_data\resources\information_extraction\competences\competences.txt'
  nocompetences_path: '..\..\quenfo_data\resources\information_extraction\competences\noCompetences.txt'
  modifier_path: '..\..\quenfo_data\resources\information_extraction\competences\modifier.txt'
  comppattern_path: '..\..\quenfo_data\resources\information_extraction\competences\competenceContexts.txt'

  tools_path: '..\..\quenfo_data\resources\information_extraction\tools\tools.txt'
  notools_path: '..\..\quenfo_data\resources\information_extraction\tools\noTools.txt'
  toolpattern_path: '..\..\quenfo_data\resources\information_extraction\tools\toolContexts.txt'

models:
  # Path to Tfidf Model and Knn Model (if not already trained, leave path to store new model)
  tfidf_path: '..\..\quenfo_data\resources\model_tfidf'
  knn_path: '..\..\quenfo_data\resources\model_knn'

# --- Tfidf Configuration ---
# Define Parameter used to train Tfidf Vectorizer
tfidf_config: 
  lowercase: False
  max_df: 1.0 
  min_df: 2
  sublinear_tf: False
  use_idf: True

# --- KNN Configuration ---
# Define Parameter used to train KNN Classifier
knn_config:
  n_neighbors: 5
  weights: 'uniform'  
  algorithm: 'auto'
  leaf_size: 30

