# +++++ Configuration ++++++
classification:
  # --- FeatureUnitConfiguration---
  fus_config:                   # Define processing steps for featureunits.
    normalize: true
    stem: true
    filterSW: true
    nGrams: {3,4}               # Generates sets of 3-Grams and 4-Grams joined in one list --> other valid options: {3} or {2,3,6} ...
    continuousNGrams: false

  # --- Data-Handling Parameters ---
  query_limit: 50               # Number of JobAds to query --> set -1 if all JobAds need to be processed
  fetch_size: 10                 # Number of JobAds per chunk
  start_pos: 0                  # Index Number of row where query starts

  # --- Model Paths ---
  models:                       #Paths to Tfidf Model and Knn Model
    tfidf_path: ..\..\quenfo_data\resources\model_tfidf 
    knn_path: ..\..\quenfo_data\resources\model_knn 

  # --- Tfidf Configuration ---
  tfidf_config:                 # Define Parameter used to train Tfidf Vectorizer
    lowercase: false
    max_df: 1.0
    min_df: 1
    sublinear_tf: false
    use_idf: true

  # --- KNN Configuration ---
  knn_config:                   # Define Parameter used to train KNN Classifier
    n_neighbors: 5
    weights: uniform
    algorithm: auto
    leaf_size: 30

# --- IE Configuration --- #
ie_config:
  type:
    competences: True
    tools: False
  start_pos: 0
  query_limit: 500
  fetch_size: 200
  expand_coordinates: True
  search: 3

# --- Paths ---
resources:
  traindata_path: ..\..\traindata_sql.db             # Path for Train data to be used for training process
  stopwords_path: ..\..\quenfo_data\resources\classification\stopwords.txt  # Path for file with stopwords
  regex_path: ..\..\quenfo_data\resources\classification\regex.txt          # Path for regex file

  # Paths for information extraction
  competences_path: ..\..\quenfo_data\resources\information_extraction\competences\competences.txt
  nocompetences_path: ..\..\quenfo_data\resources\information_extraction\competences\noCompetences.txt
  modifier_path: ..\..\quenfo_data\resources\information_extraction\competences\modifier.txt
  comppattern_path: ..\..\quenfo_data\resources\information_extraction\competences\competenceContexts.txt

  tools_path: ..\..\quenfo_data\resources\information_extraction\tools\tools.txt
  notools_path: ..\..\quenfo_data\resources\information_extraction\tools\noTools.txt
  toolpattern_path: ..\..\quenfo_data\resources\information_extraction\tools\toolContexts.txt